frontend/controllers/PostController.php
<?php

namespace frontend\controllers;

use app\models\Postings;

class PostController extends \yii\web\Controller
{
    public function actionGet($name)
    {   
        $dataProvider=Postings::find()->where(['name'=>$name])->one();
        return $this->render('get',['dataProvider'=>$dataProvider]);
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionView()
    {
        return $this->render('view');
    }

}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\data\ActiveDataProvider;
use yii\db\Query;
use app\models\News;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc

     [
                'class' => 'yii\filters\PageCache',
                'only' => ['index','news'],
                'duration' => 60,
                'variations' => [
                    \Yii::$app->language,
                ],
                'dependency' => [
                    'class' => 'yii\caching\DbDependency',
                    'sql' => 'SELECT COUNT(*) FROM news',
                ],
            ],
     */

    public $layout = 'column';


    public function behaviors()
    {
        return [
            
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionNews()
    {
        $dataProvider=News::findAll(['state'=>1]);

        return $this->render('news',['dataProvider' => $dataProvider,]);
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->getSession()->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->getSession()->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->getSession()->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

frontend/views/layouts/column.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\bootstrap\Collapse;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use frontend\widgets\Alert;
use yii\widgets\Menu;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
    <?php $this->beginBody() ?>
    <div class="wrap">
                
                        
        <?php
            NavBar::begin([
                'brandLabel' => 'My Company',
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-default navbar-fixed-top',
                ],
            ]);
            $menuItems = [
                ['label' => 'Home', 'url' => ['/site/index']],
                ['label' => 'About', 'url' => ['/site/about']],
                ['label' => 'Contact', 'url' => ['/site/contact']],
                ['label' => 'News', 'url' => ['/site/news']],
            ];
            if (Yii::$app->user->isGuest) {
                $menuItems[] = ['label' => 'Signup', 'url' => ['/site/signup']];
                $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
            } else {
                $menuItems[] = [
                    'label' => 'Logout (' . Yii::$app->user->identity->username . ')',
                    'url' => ['/site/logout'],
                    'linkOptions' => ['data-method' => 'post']
                ];
            }
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => $menuItems,
            ]);
            NavBar::end();
        ?>

        <div class="row container" >
        <div class="col-md-2">
        <table>
                    <tbody><tr>
                            <td valign="top"><center><img src="/images/phone.png"></center></td>
                            <td>
                                <h6>Киев</h6>
                                <h3>(044) 370-81-96</h3>
                                <h6>Обухов / Украинка</h6>
                                <h4>(04572) 68-140</h4>
                            </td>
                        </tr>
                        <tr>
                            <td><center><img src="/images/skype.png"></center></td>
                            <td><h5>k-abonent</h5></td>
                        </tr>
                        <tr>
                            <td><center><img src="/images/email.png"></center></td>
                            <td><h5>support@ktelecom.in.ua</h5></td>
                        </tr>
                        <tr>
                            <td colspan="2"><a href="#" data-reveal-id="myModal">Есть вопрос?</a></td>
                        </tr>
                    </tbody>
                </table>

        <?php
            $menuItemsInter = [
                ['label' => 'Payments', 'url' => ['/post/get','name'=>'premium']],
                ['label' => 'Payments', 'url' => ['/site/index2']],
                ['label' => 'Payments', 'url' => ['/site/index3']],
                ['label' => 'Payments', 'url' => ['/site/index4']],
                ['label' => 'Payments', 'url' => ['/site/index4']],
                ['label' => 'Payments', 'url' => ['/site/index5']],
                
            ];
            $menuItemsTel = [
                ['label' => 'Payments', 'url' => ['/site/index1']],
                ['label' => 'Payments', 'url' => ['/site/index2']],
                               
            ];
            $menuItemsIPTV = [
                ['label' => 'Payments', 'url' => ['/site/index1']],
                ['label' => 'Payments', 'url' => ['/site/index2']],
                               
            ];

            $menuItemsAdd = [
                ['label' => 'Payments', 'url' => ['/site/index1']],
                ['label' => 'Payments', 'url' => ['/site/index2']],
                               
            ];
            echo Collapse::widget([

                'items' => [
                    [
                        'label' => 'Payments',
                        'content' => Nav::widget([
                                'options' => ['class' => 'nav nav-pills nav-stacked'],
                                'items' => [['label'=>'Payments','url'=>['/site/ind']]],
                            ]),
                        
                    ],
                    // equivalent to the above
                    [
                        'label' => 'Internet',
                        'content' => Nav::widget([
                                'options' => ['class' => 'nav nav-pills nav-stacked'],
                                'items' => $menuItemsInter,
                            ]),
                        // open its content by default
                        'contentOptions' => ['class' => 'in']
                    ],
                    // another group item
                    [
                        'label' => 'Telephone',
                        'content' => Nav::widget([
                                'options' => ['class' => 'nav nav-pills nav-stacked'],
                                'items' => $menuItemsTel,
                            ]),
                        
                    ],
                    [
                        'label' => 'IPTV',
                        'content' => Nav::widget([
                                'options' => ['class' => 'nav nav-pills nav-stacked'],
                                'items' => $menuItemsIPTV,
                            ]),
                        
                    ],
                    [
                        'label' => 'CCTV',
                        'content' => Nav::widget([
                                'options' => ['class' => 'nav nav-pills nav-stacked'],
                                'items' => [['label'=>'Payments','url'=>['/site/ind']]],
                            ]),
                        
                    ],
                    [
                        'label' => 'Additional',
                        'content' => Nav::widget([
                                'options' => ['class' => 'nav nav-pills nav-stacked'],
                                'items' => $menuItemsAdd,
                            ]),
                        
                    ],


                ]
            ]);
             
        ?>

        </div>
        <div class="content col-md-10">
        <?php 
        if (\Yii::$app->requestedRoute!='site/index') {
            echo Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]);
        }
         ?>
        <?= Alert::widget() ?>
        <?= $content ?>
        </div>
        </div>
    </div>

    <footer class="footer">
        <div class="container">
        
            <div class="box">
            <div id="fleft">
                <table>
                    <tbody><tr>
                        <td><center><img src="/images/skype.png"></center></td>
                        <td><h5>k-abonent</h5></td>
                        <td rowspan="2"><center><img src="/images/address.png"></center></td>
                        <td><h5>г. Киев</h5></td>
                    </tr>
                    <tr>
                        <td><center><img src="/images/email.png"></center></td>
                        <td><h5>support@ktelecom.in.ua</h5></td>
                        <td><h5>ул. Саксаганского 67б</h5></td>
                    </tr>   
                </tbody></table>
            </div>
            <div id="fright">
                <table>
                    <tbody><tr>
                        <td>
                            <h6>Киев</h6>
                            <h3>(044) 370-81-96</h3>
                        </td>
                        <td>
                            <h6>Обухов / Украинка</h6>
                            <h4>(04572) 68-140</h4>
                        </td>
                        <td><center><img src="/images/phone.png"></center></td>
                    </tr>
                </tbody></table>
            </div>
            </div>
        
        </div>
    </footer>

    <?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

frontend/views/layouts/main.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use frontend\widgets\Alert;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
    <?php $this->beginBody() ?>
    <div class="wrap">
        <?php
            NavBar::begin([
                'brandLabel' => 'My Company',
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
                ],
            ]);
            $menuItems = [
                ['label' => 'Home', 'url' => ['/site/index']],
                ['label' => 'About', 'url' => ['/site/about']],
                ['label' => 'Contact', 'url' => ['/site/contact']],
                ['label' => 'News', 'url' => ['/site/news']],
            ];
            if (Yii::$app->user->isGuest) {
                $menuItems[] = ['label' => 'Signup', 'url' => ['/site/signup']];
                $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
            } else {
                $menuItems[] = [
                    'label' => 'Logout (' . Yii::$app->user->identity->username . ')',
                    'url' => ['/site/logout'],
                    'linkOptions' => ['data-method' => 'post']
                ];
            }
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => $menuItems,
            ]);
            NavBar::end();
        ?>

        <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
        </div>
    </div>

    <footer class="footer">
        <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>
        <p class="pull-right"><?= Yii::powered() ?></p>
        </div>
    </footer>

    <?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>